# Generated by Django 3.1.7 on 2021-04-06 11:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210405_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Fiction', 'Fiction'), ('History', 'History'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Western', 'Western')], max_length=124),
        ),
    ]
